FROM node:11
WORKDIR /usr/app
COPY package*.json ./
RUN npm install --production
COPY webpack.prod.config.js ./
COPY tsconfig.json ./
COPY ./src ./src
RUN npm run build:prod
EXPOSE 8443 8080 9229
CMD [ "node", "dist/server.js"]
