version: "2"
services:
  web:
    env_file:
      - variables.dev.env
    build:
      context: .
    image: 'menus-api:dev'
    command: npm run serve:dev
    volumes:
      - .:/usr/app/
      - ./node_modules:/usr/app/node_modules
    ports:
      - "49161:8080"
      - "49162:9229"
    container_name: 'menus-api-dev'
